let hotelSuggestions = [
  "Channel",
  "CodingLab",
  "CodingNepal",
  "YouTube",
  "YouTuber",
  "YouTube Channel",
  "Blogger",
  "Bollywood",
  "Vlogger",
  "Vehicles",
  "Facebook",
  "Freelancer",
  "Facebook page",
  "Designer",
  "Developer",
  "Web Designer",
  "Web Developer",
  "Login Form",
  "How to learn Javascript",
  "What does HTML stand for?",
  "What does CSS stand for?",
];
